### ISSUE TITLE
Vertaisarvionti #1

### ISSUE THREAD

**Issue by JVS23** [Peikkohi/pokemon-tietokanta#1]
Vertaisarviointi tehty 06/02/2023 12:00 kloonatun repon perusteella

Asensin sovelluksen lokaalisti, ja sain sen melko vaivatta toimimaan. Merkittävä osa toteutuksesta vaikuttaisi vielä olevan kesken, joten kehityksenaikaisia bugeja löytyy jonkin verran, joten koitan keskittyä niihin toimintoihin mitä on hyödyllistä kommentoida. README:n suunnitellut toiminnot vaikuttavat fiksuilta. Koodi itsessään selkeää luettavaa.

### Huomioita: 

- Scheman Monsters-tablesta puuttuu species-kolumni, jonka puutteen vuoksi sovellus ei aluksi käynnistynyt
- test-data.sql ei vaikuttanut toimivan Monsters-insertin kohdalta, mutta manuaalisesti frontin kautta insertit tosin vaikuttaisivat toimivan, hyvä!
- Routet voisi kokeilla eriyttää omaan app.py:stä omaan moduuliinsa kun ehdit mitä aiemmin rakenteelliset muutokset tekee sitä helpompaa se on sekä enemmän siitä hyötyy.
- Alkeellisia virheenkäsittelijöitä tai edgecasejen varatoimenpiteitä voisi lisätä, jotta virheistä ei tule suoraan internal server erroria
- README viittaa "requirements.txt":iin, mutta tiedosto on "requirement.txt", pieni typo vain mutta voi aiheuttaa seuraavalle vertaisarvioijalle hämmennystä.

### Yhteenveto:

Projekti on vielä melko alussa, mutta rakenteita on jo jonkin verran kasassa ja kun ne ovat kunnossa siitä onkin melko suoraviivaista jatkaa eteenpäin. Vinkkinä voisin suositella kokeilemaan vain pienen osan toteuttamista kerrallaan. Näin on helppo pysyä muutoksista kärryillä, ja jos joku toiminnallisuus hajoaakin yllättäen, on syypää usein nopea löytää. 

Kiinnostava projekti, tsemppiä jatkoon!

**Comment by Peikkohi** [comment]
Anteeksi, mutta mitä hyötyä koet tulevan siitä, että eriyttää routet `app.py`:stä? Jos kaikki routet on erillisiä tiedostoja, niin niitä on vaikeampi hallinnoida (routen sisäisen koodin on syytä muutenkin olla lyhyt). Jos taas haluat `routes.py` tiedoston, niin sitä en koe järkevänä, koska koodin entrypoint `app.py` olisi lähes tyhjä. Tämä suoraan lisää hallinnoitavia tiedostoja, joka minusta vaikuttaa huonolta idealta.

Uskon, että muutokselle voi olla järkeviä syitä, mutta en keksi niitä itse.

**Comment by JVS23** [comment]
Käytännössä asiasta ei tule mitenkään sovelluksen toiminnalle funktionaalista hyötyä, mutta yleisesti ottaen koodin eriyttäminen omiin moduuleihinsa, esimerkiksi routejen tapauksessa, on melko standardisoitua siistin koodin käytäntöjen mukaista toimintaa. Tosiaan app.py onkin sen jälkeen melko tyhjä, mutta varsinkin suurissa projekteissa tästä moduuleihin eristämisestä on paljon apua. [Täältä](https://hy-tsoha.github.io/materiaali/osa-3/#sovelluksen-rakenne) löytyy jotakin tietoa moduuleista, ja netistä lisää jos aihe kiinnostaa.

**Comment by Peikkohi** [comment]
Jees, kiitos.
